### ISSUE TITLE
Control setpoint from sinope-130

### ISSUE THREAD

**Issue by tracedebrake** [claudegel/sinope-130#106]
Hello @claudegel,

Is there a way to increase or decrease thermostats setpoints by using sinope-130? I can see the setpoint as a state attribute (''temperature:'') field but I don't see any Neviweb service that could change a setpoint.

My goal would be to bypass the Sinopé Neviweb app for all automatisations, such as decreasing thermostats temperature during the night and increasing them next morning by using Home Assistant only.

Thank you very much for all your work.

**Comment by claudegel** [comment]
Hi, it is pretty easy with the service climate.set_temperature. Here is an exemple:
```
###########################
##       alumer plancher cuisine a 8:00 AM en semaine
###########################
  - alias: chauffe cuisine matin
    initial_state: true
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: or
          conditions:
          - condition: state
            entity_id: sensor.season
            state: 'winter'
          - condition: numeric_state
            entity_id: sensor.dark_sky_temperature
#            entity_id: sensor.owm_temperature
            below: 3.0  
    action:
      service: climate.set_temperature
      entity_id: climate.neviweb130_climate_plancher_cuisin
      data:
        temperature: 21
```
I don't use neviweb automation as HA is a lot more powerfull.
The exemple above is done the old way with manual coding in automation.py but an easier way is to install scheduler-component with HACS. This nice component will allow you to do all your dream in automation the easy way.
Let me know if you need help
