### ISSUE TITLE
Service set_climate_keypad_lock not working

### ISSUE THREAD

**Issue by jeffreychausse** [claudegel/sinope-130#135]
Hi Claude,

It seems like the custom service _set_climate_keypad_lock_ is not working. I've tested it through the dev tools section, the service executes fine, but my thermostat (TH1123WF) keypad lock state does not update from this command. Here's the YAML configuration for the service:

```
service: neviweb130.set_climate_keypad_lock
data:
  entity_id: climate.basement_thermostat
  lockKeypad: locked
```
Thanks
