### ISSUE TITLE
Flow Data from FS4220 Not Coming In

### ISSUE THREAD

**Issue by tsniezek** [claudegel/sinope-130#148]
Hi... 
Just bought the fs4220 3/4" and va4220wf. The water switch appears and works fine in home assistant, but the fs4220 doesn't seem to populate any data. I checked model number in the debug log and it appears as 3150 which is in the list already. Neviweb shows data fine in the app and online, but I get nothing in home assistant. Any advice?

**Comment by claudegel** [comment]
Hi if you go into development tools, states. For your valve you should see those attributes:
hourly_flow_count,
daily_flow_count
monthly_flow_count
hourly_flow
daily_flow
monthly_flow

Are they populated with data

**Comment by claudegel** [comment]
Can you edit file switch.py on line number 989 which is
`#                _LOGGER.warning("%s device_hourly_stats = %s", self._sku, device_hourly_stats)`
and remove just the # to activate logging. This will allow to see what you receive from Neviweb
put in your configuration.yaml the following line to have logging.
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
Then restart HA wait few minutes for stats to start polling data and check in your home-hassistant.log to see line
FF4220WF device_hourly_stats....

**Comment by tsniezek** [comment]
Numbers are populating under the meter but not pulling into sensor information...
![meter data](https://user-images.githubusercontent.com/67398811/230133726-e1febfbe-d32a-48f7-b999-200e97d008a6.PNG)
They appear as unknown. I've probably just messed something up in the yaml I'm assuming.
![sensor data](https://user-images.githubusercontent.com/67398811/230133755-620179bb-8e36-4169-95f6-3b78a72b2f17.PNG)

**Comment by claudegel** [comment]
Ok then it is just a matter of creating a template sensor. You have two choice:
```
template:
  - sensor:
      - name: "Sedna Water Flow"
        unique_id: sensor.sedna_water_flow
        unit_of_measurement: "m³"
        device_class: water
        state_class: total_increasing
        state: >-
          {{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") }}
```
```
template:
  - sensor:
      - name: "Sedna Water Flow"
        unique_id: sensor.sedna_water_flow
        unit_of_measurement: "m³"
        device_class: water
        state_class: total
        state: >-
          {{ state_attr("switch.neviweb130_water_valve","hourly_flow") }}
```
Just change the name switch.neviweb130_water_valve for what you have for your valve
