### ISSUE TITLE
Affichage dans une Liste d'entités

### ISSUE THREAD

**Issue by gvhomeassistant** [claudegel/sinope-130#178]
Bonjour
Ce n'est pas vraiment un probleme, mais j'essaye d'arranger un peu mon dashboard et je voudrais savoir si il est possible d'afficher des éléments comme la température actuelle de l'eau ou la puissance instantannée consommée dans une "entités" (la liste)
Merci par avance !

**Comment by claudegel** [comment]
Je suppose que vous parlez d'un DM3500ZB
La température de l'eau et la demande instantanée.
Dans Outils de développement / etats vous trouverez votre calypso affiché comme ceci:
switch.neviweb130_switch_nom_de_votre_calypso
A la droite du nom de votyre appareil il y a une liste des attributs qui lui sont propre:
la température de l'eau est Water_temperature et la puissance instantanée est Wattage_instant.
pour afficher ces données dans votre dashboard il suffit alors de créer des template sensor comem ceci
dans configuration.yaml ajoutez ceci:
`template: !include template.yaml`
creez ensuite un fichier template.yaml dans le répertoire de base, config
dans template.yaml ajoutez ceci:
```
  - sensor:
     - name: "watt_chauffe_eau"
       unit_of_measurement: 'W'
       device_class: power
       state_class: measurement
       unique_id: sensor.watt_chauffe_eau
       state: "{{ state_attr('switch.neviweb130_switch_calypso_chauffe_eau_2', 'Wattage_instant') }}"
    - name: "temperature_eau"
      unit_of_measurement: '°C'
      device_class: temperature
      state_class: measurement
      state: "{{ state_attr('switch.neviweb130_switch_calypso_chauffe_eau_2', 'Water_temperature') }}"
```
Ensuite vous pourrez ajouter vos template sensor dans votre dash board comme ceci:
sensor.temperature_eau
sensor.watt_chauffe_eau
