### ISSUE TITLE
TH1124WF Missing Power/Energy

### ISSUE THREAD

**Issue by rj45jack** [claudegel/sinope-130#184]
I'm unable to find or see the power/energy usage of the TH1124WF within HA. This worked last winter AFAIK. The climate function works as intended, I am able to utilize the heat and set temps.

Using dev-tools template editor:

```
template:
  - sensor:
      - name: "Basement energy usage"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total
        state: >-
          {{ state_attr("climate.neviweb130_climate_thermostat","hourly_kwh") }}
```

Reports nothing. Not sure what happened. I reinstalled, double checked the above code and read the documentation. 

Here is my config yaml snippet:
```
neviweb130:
  username: "x"
  password: "x"
  scan_interval: 360
  homekit_mode: False  
```

**Comment by claudegel** [comment]
can you edit neviweb130 locally ? We need to activate the logging for energy stat
In conffiguration.yaml add this
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
then if you can, edit custom_components/neviweb130/climate.py
on line 1102 just remove the # at the biginning and restart HA. This will show what we receive from neviweb for energy stats
