### ISSUE TITLE
Installation de Neviweb130

### ISSUE THREAD

**Issue by matsam8895** [claudegel/sinope-130#204]
Bonjour Claude,
Je n'ai pas vraiment aucune expérience en programmation, C'est la première fois que j'essaie d'installer quelque chose d'autre que des composants de Sonoff, Tuya et TP-Link et je n'arrive pas à configurer mes thermostats Sinope avec le GT130 dans HA. Avec HACS j'ai installé Sinope Neviweb130. Dans File editor il y a custom_components/neviweb130 avec tout les fichiers, quelle est la prochaine étape? 
J'ai copié dans configuration.yaml
neviweb:
  username: '<Neviweb username>'
  password: '<Neviweb password>'
  network: '<your first location in Neviweb>' (1er emplacement)
  network2: '<your second location in Neviweb>' (2e emplacement)

Quand on met le username on laisse les < >?
Dans network on met l'adresse IP?
on efface network2?

**Comment by claudegel** [comment]
Bonjour, il faut que tu ajoute la configuration dans configuration.yaml comme ceci
```
neviweb130:
  username: !secret climate_username  <-- l'adresse courriel utilisée pour connecter à Neviweb
  password: !secret climate_password <-- le mot de passe Neviweb
  network: !secret climate_gateway130  <-- le nom de la l'emplacement dans Neviweb ou sont les appareils
  scan_interval: 360
  stat_interval: 600
```
Pour network2 c,est optionnel c'est seulement si tu as deux emplacement avec GT130, par exemple un à la maison et un au chalet.
On laisse pas les <>. Dans mon exemple j'ai mis !secret climate_username. C'est que normalement tu devrais mettre les nom d'usager et les mot de passe dans le fichier secrets.yaml qui est protégé. dans celui-ci tu met ceci:
```
climate_username: 'moi@ici.com'
climate_password: 'qwerty1234'
climate_gateway130: 'nom_de_emplacement_dans_neviweb'
```
ces informations sont entre ' ' apostrophe.
Après tu redémarre HA et ça devrait loader les appareils.
pour scan_intervalle c'est en seconde et il faut pas descendre sous 300 ni augmenter au dessus de 600 sinon tu vas te faire débrancher de Neviweb. En dessous de 300 neviweb va te blocquer.
