### ISSUE TITLE
Feature request: Manage Neviweb automations

### ISSUE THREAD

**Issue by alcos-duck** [claudegel/sinope-130#218]
Feature request:
Is it possible to manage (aka turn on/off) automations groups and individual automations?

![Screenshot_20240211_072649_Neviweb](https://github.com/claudegel/sinope-130/assets/149615881/ab6c458d-3679-4427-be6f-bcd5458b2839)
![Screenshot_20240211_072722_Neviweb](https://github.com/claudegel/sinope-130/assets/149615881/e6ffe56d-9682-41b7-b2bd-882f05f194bc)
![Screenshot_20240211_072813_Neviweb](https://github.com/claudegel/sinope-130/assets/149615881/b742170d-baea-4a7e-a72f-2ef5cf74fe92)
Best regards,

**Comment by claudegel** [comment]
It will be hard to set that as the commande to turn_on or turn_off an automation is not a single commande like turn_on automation_name. We have to send each time the complete description of the automation with all the devices.
Have a look at scheduler-component that can be installer via HACS. with this you can easily make all automation you want or need and it is easy to turn_on or turn_off thos automations like this:
```
service: switch.turn_on
      data:
        entity_id:
          - switch.schedule_chauffage_salon_pointe
          - switch.schedule_chauffage_salle_a_diner_pointe
          - switch.schedule_chauffe_salle_de_lavage_pointe
          - switch.schedule_chauffe_chambre_1_pointe
          - switch.Chauffe_chambre_enfant_pointe
          - switch.Chauffe_invite_pointe
          - switch.schedule_allumer_chargeur_auto_jour 
```
Every automation are registered as a switch that you can turn_on or off.
