### ISSUE TITLE
Integration no longer starting since v2.7.0

### ISSUE THREAD

**Issue by arctis-shark** [claudegel/sinope-130#233]
![image](https://github.com/claudegel/sinope-130/assets/78988923/8e42b4f4-2198-4799-8d29-ae4e5a43dd36)
![image](https://github.com/claudegel/sinope-130/assets/78988923/d006ab7c-5864-45ea-a762-dc6b82ca7bef)

I have been getting those errors ever since I updated to v2.7.0

**Comment by claudegel** [comment]
How did you upgrade. Via HACS ?
Do you have some log to show. Add this in configuration.yaml and restart HA
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
In home-assistant.log check for line like [custom_components.neviweb130] ...
you should see something about login problem or network name or other error message
Finally what are the devices you have in climate and valve
