### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by alexbd8192** [claudegel/sinope-130#236]
Hi, 

I've installed 3 new wifi thermostats (2x TH1123WF & 1x TH1124WF).
I've setup them in the app and they are working fine within their app.
I tried to setup the integration using this repo, but unfortunately the setup seems to fail.
Apparently a variable named LOCATIONS_URL return a NoneType instead of a str.

Not sure if its a 'me' problem since its the first time I am using it, and I read the documentation on how to set it up.

Any ideas?

Thanks!

System info:
Core
2024.3.3
Frontend
20240307.0

HA install on Unraid, via docker.

Yaml config:
`neviweb130:
  username: 'me@email.com'
  password: 'mypassword'
  scan_interval: 360
  homekit_mode: False
  stat_interval: 1800`

Debug Log:
`Logger: homeassistant.setup
Source: setup.py:390
First occurred: 9:00:19 AM (1 occurrences)
Last logged: 9:00:19 AM

Error during setup of component neviweb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 77, in setup
    data = NeviwebData(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 101, in __init__
    self.neviweb_client = NeviwebClient(username, password, network, network2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 133, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb/__init__.py", line 178, in __get_network
    raw_res = requests.get(LOCATIONS_URL + self._account, headers=self._headers,
                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by claudegel** [comment]
Look like you've install the wrong custom_component. There are two:
- neviweb for the old miwi devices. in hacs Sinope Nevweb
- neviweb130 for the zigbee and wifi devices. In hacs Sinope neviweb130
Also post your config in configuration.yaml
should be:
```
neviweb130:
  username: !secret climate_username  <-- email used to log into Neviweb
  password: !secret climate_password  <-- neviweb password
  network: !secret climate_gateway130  <-- Neviweb location name where are your devices
  scan_interval: 360
  stat_interval: 600
```
