### ISSUE TITLE
Normalisation du nommage des attributs

### ISSUE THREAD

**Issue by biereluc** [claudegel/sinope-130#244]
## Problémaique
Le nommage des attributs n'est pas standard d'un device à un autre. Par exemple des attributs du **RM3500ZB** commencent par une majuscule et donc doivent être appellé dans les templates avec la case sensible. Par contre votre standard dans bien autres devices est de toujours mettre l'attribut en minuscule.

### Exemple wattage_instant:
Avec le **RM3500ZB**, appeler wattage_instant en minuscule génère une erreur
``` yaml
{% states.switch.neviweb130_switch_chauffe_eau.attributes.wattage_instant %}
```
![image](https://github.com/claudegel/sinope-130/assets/38539800/91578005-144d-4620-8229-fdaee8aa7d16)

Il faut l'appeler avec le **W** majuscule : 
``` yaml
{% states.switch.neviweb130_switch_device1.attributes.Wattage_instant %}
```
Mais il faut appeler avec un **w** minuscule avec un **RM3200RF**
``` yaml
{% set wattage = states.switch.neviweb_switch_device2.attributes.wattage_instant %}
```

Il devient difficile de faire des scripts qui appellent un même attribut qui se retrouve dans tous les appareils Neviweb peu importe les modèles. Comme par exemple **wattage** qui est en minuscule dans bien des appareils et en majuscule dans le **RM3500ZB**.

## Votre norme générale
Votre standard de nommage général pour d'autre produit GT125 ou GT130 commence par des minuscules, sauf quelques attributs qui se sont peut-être glissés avec le temps dans des mises à jour, entre autre _Activation_.

### Exemples 
``` yaml
#  RM3200RF / GT125 (TOUT en minuscule)
operation_mode: manual
eco_status: none
rssi: 30
timer: 0
occupancy: home
away_mode: auto
keypad: unlocked
wattage: 0    #   <----- Exemple OK
wattage_instant: 0   #   <----- Exemple OK
hourly_kwh: 0
daily_kwh: 0
sku: RM3200RF
device_class: power
icon: mdi:pool
friendly_name: Device 2

# Versus un RM3500ZB / GT130 (Un peu aléatoire)
onOff: on
Wattage: 4335   #   <----- Exemple PAS STANDARD
Wattage_instant: 0   #   <----- Exemple PAS STANDARD
hourly_kwh_count: 5364.141
daily_kwh_count: 5363.141
monthly_kwh_count: 5205.669
hourly_kwh: 0.105
daily_kwh: 1.105
monthly_kwh: 158.577
Water_leak_status: ok    #   <----- 
Water_temperature: 49.75    #   <----- 
Cold_load_pickup_status: 1    #   <----- 
Cold_load_remaining_time: off    #   <----- 
Tank_size: 60 gal    #   <----- 
Temperature_status: null    #   <----- 
Stm_Mcu: null    #   <----- 
Thermal_overload: null    #   <----- 
Current_overload: null    #   <----- 
j2Connector: null
j3Connector: null
Line_error: null    #   <----- 
eco_status: off
eco_optOut: off
eco_onoff: off
eco_optout_reason: off
Water_temp_min: 45    #   <----- 
Water_time_on: 240    #   <----- 
Water_temp_time: 2    #   <----- 
Protection_Temperature: ok    #   <----- 
Protection_Consumption: ok    #   <----- 
Protection_consumption_overtime: ok    #   <----- 
Rssi: -64    #   <----- 
sku: RM3500ZB
device_model: 2151
device_model_cfg: 0
firmware: 0.3.3
Activation: true    #   <----- 
device_type: power
device_class: switch
icon: mdi:water-boiler
friendly_name: Device 1
```
### Autres exemples plus standard
``` yaml
# TH1300ZB / GT130
hvac_modes: heat, off
min_temp: 5
max_temp: 30
preset_modes: away, none
current_temperature: 23.1
temperature: 22.5
hvac_action: idle
preset_mode: none
wattage: 2172
[...]
sku: TH1300ZB
device_model: 737
device_model_cfg: 0
firmware: 1.2.0
Activation: true    #   <----- 
id: 399292
unit_of_measurement: °C
device_class: temperature
friendly_name: Devide 4
supported_features: 401

# TH1300ZB / GT130
hvac_modes: heat, off
min_temp: 5
max_temp: 30
preset_modes: away, none
current_temperature: 23.1
temperature: 22.5
hvac_action: idle
preset_mode: none
wattage: 2172
[...]
sku: TH1300ZB
device_model: 737
device_model_cfg: 0
firmware: 1.2.0
Activation: true    #   <----- 
unit_of_measurement: °C
device_class: temperature
friendly_name: Device 3
supported_features: 401
```
De règle générale, les appareils et les attributs de plus utilisés sont toujours en minuscule dans vos définitions. J'ai trouvé toutefois quelques appareils où certains attributs sont en majuscule et minuscule (Pour les appareils que je possède), les voici :
- [x] DM2500ZB
- [x] RM3500ZB
- [ ] GT125
- [ ] GT130
- [x] TH1300ZB
 
Merci pour votre bon travail.
