### ISSUE TITLE
BacklightAdaptative not working

### ISSUE THREAD

**Issue by piluc88** [claudegel/sinope-130#259]
Hello Claude i don't know where to write this but i want to put the backlight off on two sinope thermostat only when i try the action in developper i have no error but when i go see the the thermostat backlight is still on. Can you help me.

Thanks

**Comment by claudegel** [comment]
Yes, what is the thermostat model you want to switch the backlight off. It differ between zigbee and wifi

**Comment by piluc88** [comment]
TH1124ZB they are all zigbee

**Comment by claudegel** [comment]
ok but they are not G2 model ? because G2 have another config called bedroom. With this, the backlight is on during the day and off at night.
```
action: neviweb130.set_backlight
data:
  entity_id: climate.neviweb130_climate_office
  type: zigbee
  backlightAdaptive: auto 
```
you have value 'on', always on and 'auto', turn on when you touch the thermostat button

**Comment by claudegel** [comment]
maybe you need quote
```
action: neviweb130.set_backlight
data:
  entity_id: climate.neviweb130_climate_office
  type: "zigbee"
  backlightAdaptive: "auto" 
```
Don't remenber

**Comment by claudegel** [comment]
I ned to update the doc as now services all called action. Will do it this weekend

**Comment by piluc88** [comment]
ok thanks but i try with quote and no quote nothing happen when i click to perform the action i have a green check. Do you have another place i can configure the backlight. How do i know if they are not G2 or G2?

**Comment by piluc88** [comment]
or maybe it is because before i was using the gt-130 and now i'm directly connected to my Home assistant so i need to use your other repo?

**Comment by claudegel** [comment]
Ok I've tested this and it give me an error: mapping values are not allowed here
```
##########################
##  test backlight
##########################
  - id: gestion_backlight
    alias: gestion backlight
    initial_state: True
    trigger:
      platform: time
      at: "12:05:00"
    condition: []
    action: climate.neviweb130.set_backlight
      data:
        entity_id: "climate.neviweb130_climate_cave"
        type: "zigbee"
        backlightAdaptive: "auto"
    mode: single
```
Let me check a little bit mor to clear that error

**Comment by claudegel** [comment]
If you are not using the GT130 then you have a zigbee gateway and are using ZHA or Zigbee2Mqtt.
This is different. Tell me more, zha or z2m

**Comment by piluc88** [comment]
I’m using ZHA

thanks

**Comment by claudegel** [comment]
OK in ZHA there are two way to do this.
- if you want the change to be permanent just wright the data in the attribute/cluster directly in your device.
- This is cluster 0x0201, attribute 0x0402, data: OnDemand: 0, Always on: 1

![zigbee](https://github.com/user-attachments/assets/98cbb43e-74b2-42c2-862c-601f69332f52)
![zigbee1](https://github.com/user-attachments/assets/6142bebd-433c-4bfb-8046-6dd4c20a0a01)
![zigbee2](https://github.com/user-attachments/assets/dc4120ba-9cd7-4adf-b3a6-c68954a4f035)

**Comment by claudegel** [comment]
- if you want to switch between on and off then you need to do an automation like this:
Let say you want to swith backlight to off at 20:00 PM
```
- id: set_backlight_off
  alias: set_backlight_off
  trigger:
    - platform: time
      at: "20:00:00"
  variables:
    thermostats:
      - 50:0b:91:40:00:02:26:6d <- This is the IEEE of your device. One per line if you have many
      - 38:5c:fb:ff:fe:d9:ea:f4
  action:
    - repeat:
        count: "{{thermostats|length}}"
        sequence:
          - service: zha.set_zigbee_cluster_attribute
            data:
              ieee: "{{ thermostats[repeat.index-1] }}"
              endpoint_id: 1
              cluster_id: 0x0201
              cluster_type: in
              attribute: 0x0402
              value: 0
  mode: single
```
You can do another one to turn on the backlight in the morning
