### ISSUE TITLE
RM3500WF detected as a switch but there is no sensor to track temperatures

### ISSUE THREAD

**Issue by tessierp** [claudegel/sinope-130#261]
Hi,

I recently installed Neviweb130, works fantastically well with Sinope thermostats I have. Amazingly well done!

Recently I installed a water tank controller, RM3500WF. A switch was detected by Home Assistant to turn it on and off however there doesn't seem to be any support in Neviweb130 to keep track of the temperature sensor. Any idea why?

**Comment by claudegel** [comment]
The RM3500WF is fully supported in neviweb130. The water temperature is reported as attribute water_temperature
You just need to create a template sensor to track that attribute
```
template:
  - sensor:
      - name: "temperature_eau"
        unique_id: sensor.temperature_eau
        unit_of_measurement: '°C'
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('switch.neviweb130_switch_calypso_chauffe_eau', 'water_temperature') }}"
```
replace the last line by the name of your device. Should work without problem.
