### ISSUE TITLE
Error during setup of component neviweb130

### ISSUE THREAD

**Issue by casamtl** [claudegel/sinope-130#289]
Hi. Trying to get neviweb130 set up. I'm a first time user. Added the configuration.yaml entry (although I'm unsure about the format in your sample—'«your Neviweb username»'—perhaps there's a problem when I used single quotes online.

Thanks for any help.

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 2:09:06 PM (1 occurrences)
Last logged: 2:09:06 PM

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/__init__.py", line 150, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
  File "/config/custom_components/neviweb130/__init__.py", line 188, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network, network2, network3)
                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 223, in __init__
    self.__get_gateway_data()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/neviweb130/__init__.py", line 375, in __get_gateway_data
    data = self.get_device_attributes(device["id"], [ATTR_SIGNATURE])
                                      ~~~~~~^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by claudegel** [comment]
Hi welcome to HA. This error is just because you entered the wrong credential for Neviweb
In configuration.yaml you need to add the following
```
neviweb130:
  username: 'your Neviweb email'
  password: 'your neviweb password'
  network: 'location name where is your GT130 or wifi dev are'
  network2: 'net name 2'   <-- can omit this line if only one network
  network3: 'net_name3'   <-- can omit this line if only one network
  scan_interval: 360    <- the last three lines are facultatives
  stat_interval: 600
  notify: "notification"
```
IF you omit lines scan_interval, stat_interval and notify, they will be populated with the default values.
If you don't have a GT125 network you can also omit the three network parameters as neviweb130 will find them automatically. But if you have a network for an old GT125 you need to specify the loaction name for your GT130 and/or wifi devices. Don't put the location name of your GT125 if you have one as it is suported by another custom_component sinope-1

let me know

**Comment by claudegel** [comment]
![Image](https://github.com/user-attachments/assets/cc998d73-7a68-48fa-94a7-ee70b828781b)

**Comment by casamtl** [comment]
Thanks for the quick response, Claude. I tried updating and still get the error on login after restart. I’m clear still entering something wrong. My home assistant/configuration.yaml reads:

neviweb130:
  username: ***@***.***'
  password: ‘xxxxx'
  network: 'Piano'
  scan_interval: 360
  stat_interval: 1800
  notify: "notification"

Should network be “GT130 - Piano”, which is the full title on my Neviweb app page for the gateway?

**Comment by claudegel** [comment]
If Piano is the name at the top of the Neviweb page it is OK. Your at the step gateway_data so your login and password are OK.
Put this in configuration.yaml
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
Then restart HA and check at the top of home-assistant.log
you should see the following lines
1- [custom_components.neviweb130] Login response:.... 
2- [custom_components.neviweb130] Successfully logged in to:...
3- [custom_components.neviweb130] Number of networks found on Neviweb:...  <-- you should see your network name
4- [custom_components.neviweb130] Selecting xxx network among:    <- xxx should be Piano
5- [custom_components.neviweb130] Received gateway data: [...  <-- this line contain all your devices with there model number

Check this and let me know.
