### ISSUE TITLE
Setup stock at "custom_components/neviweb130/__init__.py:199"

### ISSUE THREAD

**Issue by jlaf1** [claudegel/sinope-130#30]
Hi. I did the setup using HACS repositoty.

I am getting the following error:

Logger: homeassistant.setup
Source: custom_components/neviweb130/__init__.py:199
First occurred: 8:47:01 (1 occurrences)
Last logged: 8:47:01

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/__init__.py", line 74, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
  File "/config/custom_components/neviweb130/__init__.py", line 97, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network)
  File "/config/custom_components/neviweb130/__init__.py", line 124, in __init__
    self.__get_gateway_data()
  File "/config/custom_components/neviweb130/__init__.py", line 199, in __get_gateway_data
    data = self.get_device_attributes(device["id"], [ATTR_SIGNATURE])
TypeError: string indices must be integers

**Comment by claudegel** [comment]
Hi @jlaf1, what did you put in configuration.yaml ?
you need this:
```
neviweb130:
  username: 'email to log into Neviweb'
  password: 'password to log into Neviweb'
  network: 'Name of the location in Neviweb where are your GT130 devices'
  scan_interval: 360
```
check your log to find line like this one
`[custom_components.neviweb130] Selecting xxxxx network among: [{'id': 12788, 'location$id': None, 'group$id': None, 'name': 'xxxxx',`
where 'name': 'xxxxx' is the name of the location you need to put in your configuration.yaml
network: 'xxxxx'
