### ISSUE TITLE
Missing energy information

### ISSUE THREAD

**Issue by isbkch** [claudegel/sinope-130#34]
I couldn't find any sensor that exposes energy consumption although I have access to that info in the Neviweb portal. Is it by design or am I missing something ?

**Comment by isbkch** [comment]
First of all, thank you for taking the time to provide such detailed answer. 

I'm trying to estimate the cost for a sinope-130 thermostat. I'm able to do the calculation for other devices using the `platform: integration` but the only entity I'm able to see is the `climate.neviweb130_climate_thermostat` how did you get the wattage entities in your example?

**Comment by claudegel** [comment]
Hi. To get data from sinope-130 devices I create a sensor like this:
```
- platform: template
  sensors:
    watt_chauffe_eau:
        friendly_name: "Chauffe eau"
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('switch.neviweb130_switch_chauffe_eau', 'current_power_w') }}"
```
Then I'm using it in my histoty graph like this in lovelace:
```
- type: history-graph
        title: Historique consommation énergivores
        entities:
          - sensor.watt_chauffe_eau
          - sensor.chargeur_auto_electrical_measurement
        hours_to_show: 24
        refresh_interval: 0
```
For your thermostat the sensor would be 
```
- platform: template
  sensors:
    watt_thermostat:
        friendly_name: "My thermostat"
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('climate.neviweb130_climate_plancher_cuisine', 'wattage') * (state_attr('climate.neviweb130_climate_plancher_cuisine', 'heat_level')/100) }}"
```
The wattage attribute is the measured load on the thermostat but as you never heat at 100% power, you need to divide the wattage by the heat_level attribute which is the percentage of heating.
To find all available attribute for your devices simply check in dev tool for your devices.
![attributes](https://user-images.githubusercontent.com/4268938/138008912-f045e858-b9d4-4bc3-95c4-6985b5ac0595.png)
