### ISSUE TITLE
Not showing in integrations and the Thermostats are not being listed as Devices

### ISSUE THREAD

**Issue by OptimAdam** [claudegel/sinope-130#55]
Hi,

I wanted to check if this is expected behavior.

I have downloaded the project via HACS and I see it in HACS integrations but when I go to HAs integration its not listed. Other project I have installed normally show up in both places.

The other issues I have is all the Thermostats  (th1500zb) show up as entities and not devices. This is making it difficult to automate and control the units.

Please let me know if this is by design or if I have missed something during setup

Thanks

**Comment by claudegel** [comment]
Hi, 

neviweb130 is not a component so it won't show up in HA integration. It is a custom_component and it is installed by HACS in 
config/custom_components/neviweb130.
If you've done the config in configuration.yaml it will load at startup of HA and create entities for your thermostats in dev tools. You will find there your devices listed as climate.neviweb130_climate_your_thermostat_name.
If it's there then you just need to add a card in the overview panel using lovelace configuration.
Go to overview panel and clic on the three dots in the upper right corner. Then clic on the blue button in the bottom right corner to add a lovelace card. select a thermostat card and follow the instruction to add your devices there. You should then be able to see your thermostats in the overview panel.
For automations you need to use the entity name of your thermostats
You can add in configuration.yaml the following for debug purpose:
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```

**Comment by OptimAdam** [comment]
Thanks claudegel, 

It sounds like I have it set up right, I can see and control them via the cards.

I need to workout how I set the temperature of the thermostats using automation.

Thanks

**Comment by claudegel** [comment]
For automations you can do it the old way by writting small code like this:
```
#################################
###       winter room heating
#################################
  - id: heat_room_morning
    alias: lower room temp morning
    initial_state: true
    trigger:
      platform: time
      at: "06:45:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: climate.neviweb130_climate_room_1
          state: 'heat'
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.season
              state: 'winter'
            - condition: numeric_state
              entity_id: sensor.dark_sky_temperature
              below: 3.0
    action:
      - service: climate.set_temperature
        entity_id:
          - climate.neviweb130_climate_room_1
        data:
          temperature: 18
```
first you need to add in configuration.yaml 
`automation: !include_dir_merge_list automation/`
Then create a dir named automation and in that dir add all file *.yaml where you will put your code as above
There is plenty of doc for each line of the code exemple above.

Another way is to learn the automation via th eside pannel: configuration -> automations and scenes
Lot of fun for cold winter time
